name: 'Setup Steps'
description: 'This action setups all the common libraries and authentication'

runs:
  using: 'composite'
  steps:
    - name: 🐢 Install pnpm 🐢
      uses: pnpm/action-setup@v4
      with:
        version: 9
        run_install: false

    - name: 🐢 Setup Node 🐢
      uses: actions/setup-node@v6
      with:
        node-version: 23
        cache: pnpm

    - name: 🐢 Install Node Package Dependencies 🐢
      shell: bash
      run: pnpm install

    - name: 🐢 Install SF CLI 🐢
      uses: svierk/sfdx-cli-setup@main
